name: aria2
enable: true
priority: 70
height: 6
padding: 3
extend:
  Host:
    val: 127.0.0.1
    desc: IP
    priority: 200
  Port:
    val: 6800
    desc: 端口
    priority: 100
  Token:
    val: prc_password
    desc: 密钥
    priority: 0