# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: push到腾讯云

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 上传到香港
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.XG_HOST }} # 服务器域名
        username: ${{ secrets.SSH_USER }} # 腾讯云默认用户名为root
        key: ${{ secrets.SSH_KEY }} # 本地.ssh文件下的私钥id_rsa，存在secrets中
        source: './' # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
        target: '/home/myservers/conf.d/plugin/web' # 目标目录
    # - name: 上传到硅谷
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.GG_HOST }} # 服务器域名
    #     username: ${{ secrets.SSH_USER }} # 腾讯云默认用户名为root
    #     key: ${{ secrets.SSH_KEY }} # 本地.ssh文件下的私钥id_rsa，存在secrets中
    #     source: './' # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
    #     target: '/home/myservers/conf.d/plugin/web' # 目标目录
    - name: 上传到广州
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.GZ_HOST }} # 服务器域名
        username: ${{ secrets.SSH_USER }} # 腾讯云默认用户名为root
        key: ${{ secrets.SSH_KEY }} # 本地.ssh文件下的私钥id_rsa，存在secrets中
        source: './' # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
        target: '/home/myservers/conf.d/plugin/web' # 目标目录

